//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWebDatos1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        public int Id { get; set; }
        public string CodigoHotel { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Estrellas { get; set; }
        public Nullable<int> Habitaciones { get; set; }
        public Nullable<int> Membresia { get; set; }
    }
}
